### ISSUE TITLE
Project 0

### ISSUE THREAD

**Issue by carise** [carise/simple-todo#1]
I think my app is complete. Please review. /cc @codepathreview @codepath

Still working on optional features.

**Comment by nesquena** [comment]
Carise,

Looks good, this exercise is intended in part to give you an introduction to the general rhythm of this course. The course is entirely project-based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer  learn the practical elements of Android development and best practices as quickly as possible. We also do a code review for each submitted project once the program begins.

The next step is to continue working on [extensions to your todo app](http://courses.codepath.com/snippets/intro_to_android/prework#heading-5-extending-your-todo) and to **schedule a short 15 minute phone conversation** with us. Navigate to [today's date and onward from there](https://calendar.google.com/calendar/selfsched?sstoken=UURvT01vbzBza1pnfGRlZmF1bHR8NzVjYzBkN2EyZTRiOGRmYjZlZjhmMjA2N2IyMGMwYWU) and choose an available 15-minute slot in the mornings or evenings. Let us know if none of those times work.

With regards to extensions to implement, we are looking for developers with an interest in user experience and product development so be sure to focus on additional functional enhancements and/or improving the user interface of the app.

Once you select a slot, can you make sure to **include the best number** to reach you at to the invite?

**Prior to our chat**, can you take some time to research the most common Android Activity lifecycle methods as well as the `ArrayAdapter` pattern used when working with lists? We will be discussing these topics with you conceptually in the phone call. We encourage you to [search our guides](http://guides.codepath.com/android/) as well as any other sources you'd like.

Look forward to chatting soon!

**Comment by carise** [comment]
Thanks Nathan. I made a checklist for myself below.

[ ] Add more extensions to the app
[x] Set an appointment with Codepath
[x] Provide phone number on the appointment
[ ] Research Android Activity lifecycle methods
[ ] Research ArrayAdapter pattern
